apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fhir-server.fullname" . }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fhir-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fhir-server.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "fhir-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "DataStore"
            value: {{ .Values.appSettings.DataStore }}
          - name: "FHIRServer__Security__Enabled"
            value: {{ .Values.appSettings.FHIRServerSecurityEnabled | quote }}
          - name: "SqlServer__ConnectionString"
            valueFrom:
              secretKeyRef:
                name: {{ include "fhir-server.fullname" . }}
                key: sqlConnectionString
          - name: "SqlServer__AllowDatabaseCreation"
            value: "true"
          - name: "SqlServer__Initialize"
            value: "true"

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metadata/
              port: http
          readinessProbe:
            httpGet:
              path: /metadata/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
