{{- $fullName := include "fhir-server.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-server.fullname" . }}
type: Opaque
data:
{{- if .Values.sql.deploy }}
  sqlConnectionString: {{ printf "Server=tcp:%s-sql,1433;Initial Catalog=FHIR;Persist Security Info=False;User ID=sa;Password=%s;MultipleActiveResultSets=False;Connection Timeout=30;"  $fullName  .Values.sql.sapassword | b64enc }}
{{- else }}
  sqlConnectionString: {{ .Values.appSettings.customConnectionString | b64enc }}
{{- end }}